### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Antyklimeax** [Mister-Kay/ping-compensation#6]
Getting this error when I try to use ping compensation

[dispatch] handle: error running raw hook for C_START_SKILL<raw>
hook: (anonymous) in ping-compensation
data: 32005f84f414011000000000695a1c5c8d47bb02a9465ea34f44000000000000000000000000010000000000000000000000
error: protocol.parse is not a function

[dispatch] handle: error running raw hook for C_START_SKILL<raw>
hook: (anonymous) in ping-compensation
data: 32005f84f41401100000000041649b3c8d4727a9a946e7ae5144000000000000000000000000010000000000000000000000
error: protocol.parse is not a function

**Comment by ghost** [comment]
Should be fixed now

**Comment by Antyklimeax** [comment]
Working now, thank you
